  name: Continuous Integration
  on:
    pull_request:
      branches:
        - main
  jobs:
    Explore-GitHub-Actions:
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository code
          uses: actions/checkout@v4

        - name: Python Lint Code Scanning Action
          uses: advanced-security/python-lint-code-scanning-action@v1.1.2
          with:
            linter: pylint
  
    Roda-Testes:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout do código
          uses: actions/checkout@v4

        - name: Configurar Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.12'

        - name: Configurar PYTHONPATH
          run: export PYTHONPATH=$PYTHONPATH:./src

        - name: Instalar dependências
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt 

        - name: Executar Testes Unitários
          run: |
            python -m unittest discover -s . -p "*.py"